name: fmpe-ariel
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.12
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - alabaster==1.0.0
      - altair==5.5.0
      - altair-data-server==0.4.1
      - altair-saver==0.5.0
      - altair-viewer==0.4.0
      - annotated-types==0.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arviz==0.20.0
      - astroid==3.3.8
      - astropy==6.1.7
      - astropy-iers-data==0.2025.3.3.0.34.45
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - autograd==1.7.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bilby==2.4.0
      - bilby-cython==0.5.3
      - bilby-pipe==1.5.0
      - black==25.1.0
      - bleach==6.2.0
      - blosc2==2.7.1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - chainconsumer==1.1.3
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - configargparse==1.7
      - configobj==5.0.9
      - cons==0.4.6
      - contourpy==1.3.1
      - corner==2.2.3
      - cryptography==44.0.2
      - cycler==0.12.1
      - cython==3.0.12
      - dask==2025.2.0
      - dateparser==1.2.1
      - debugpy==1.8.12
      - decorator==5.2.1
      - deepdish==0.3.7
      - defusedxml==0.7.1
      - deneb==1.0.1
      - diffeqtorch==1.0.0
      - dill==0.3.9
      - dingo-gw==0.5.5.dev3+g96f31a8.d20250304
      - distributed==2025.2.0
      - divexplorer==0.2.6
      - docker-pycreds==0.4.0
      - docutils==0.21.2
      - dqsegdb2==1.3.0
      - dynesty==2.1.5
      - elfi==0.8.6
      - emcee==3.1.6
      - etuples==0.3.9
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - flatlatex==0.15
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glasflow==0.4.1
      - gpy==1.13.2
      - gpytorch==1.14
      - greenlet==3.1.1
      - grpcio==1.70.0
      - gwdatafind==1.2.0
      - gwosc==0.7.2
      - gwpy==3.0.12
      - h11==0.14.0
      - h5netcdf==1.5.0
      - h5py==3.13.0
      - idna==3.10
      - igraph==0.11.8
      - igwn-auth-utils==1.2.0
      - igwn-segments==2.0.0
      - imagesize==1.4.1
      - importlib-metadata==8.6.1
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipyparallel==9.0.1
      - ipython==8.33.0
      - ipython-genutils==0.2.0
      - isort==6.0.1
      - jabbar==0.0.16
      - jaxtyping==0.2.38
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - julia==0.6.2
      - jupyter-cache==1.0.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - lalsuite==7.25.1
      - latexcodec==3.0.0
      - ligo-gracedb==2.13.2
      - ligo-segments==1.4.0
      - ligotimegps==2.0.1
      - linear-operator==0.6
      - linkify-it-py==2.0.3
      - llvmlite==0.44.0
      - locket==1.0.0
      - logical-unification==0.4.6
      - lscsoft-glue==4.0.0
      - mako==1.3.9
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - minikanren==1.0.3
      - mistune==3.1.2
      - mlxtend==0.23.4
      - mpld3==0.5.10
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multipledispatch==1.0.0
      - mypy-extensions==1.0.0
      - myst-nb==1.2.0
      - myst-parser==4.0.1
      - narwhals==1.29.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ndindex==1.9.2
      - nest-asyncio==1.6.0
      - nestle==0.2.0
      - netcal==1.3.6
      - networkx==3.4.2
      - nflows==0.14
      - notebook==6.4.12
      - numba==0.61.0
      - numdifftools==0.9.41
      - numexpr==2.10.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opt-einsum==3.4.0
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - paramz==0.9.6
      - parso==0.8.4
      - partd==1.4.2
      - pathspec==0.12.1
      - patsy==1.0.1
      - pegasus-wms-api==5.0.9
      - pegasus-wms-common==5.0.9
      - pesummary==1.3.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pluggy==1.5.0
      - portpicker==1.6.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyabc==0.12.15
      - pyabcranger==0.0.72
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pycbc==2.7.3
      - pycondor==0.6.0
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyerfa==2.0.1.5
      - pyfftw==0.15.0
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pykerr==0.1.0
      - pyknos==0.16.0
      - pylightcurve==4.0.4
      - pylint==3.3.4
      - pymc==5.21.0
      - pyopenssl==25.0.0
      - pyparsing==3.2.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pysocks==1.7.1
      - pytensor==2.28.2
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-igraph==0.11.8
      - python-ligo-lw==1.8.3
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - redis==5.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.23.1
      - safe-netrc==1.0.1
      - sbi==0.21.0
      - sbibm==1.1.0
      - scikit-learn==1.6.1
      - scipy==1.12.0
      - scitokens==1.8.1
      - seaborn==0.12.2
      - selenium==4.29.0
      - send2trash==1.8.3
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.3
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-mermaid==1.0.0
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.38
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tables==3.10.1
      - tabulate==0.9.0
      - taurex==3.2.2
      - tblib==3.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tikzplotlib==0.9.8
      - tinycss2==1.4.0
      - tomli==2.2.1
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchdiffeq==0.2.5
      - torchinfo==1.8.0
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trio==0.29.0
      - trio-websocket==0.12.2
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - tzlocal==5.3
      - uc-micro-py==1.0.3
      - urllib3==2.3.0
      - vega-datasets==0.9.0
      - wadler-lindig==0.1.3
      - wandb==0.19.7
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - xarray==2025.1.2
      - xarray-einstats==0.8.0
      - zict==3.0.0
      - zipp==3.21.0
      - zuko==1.4.0
