dataset:
  path: sbi-ariel/data
  type: RealFullNormalizedArielDataset
evaluation:
  aux_data: ARIEL/TrainingData/AuxillaryTable.csv
  beta: 0.8
  cia_path: ARIEL/ADC_t3_input/cia/HITRAN
  n_quantiles: 10
  n_repeats: 2048
  opacity_path: ARIEL/ADC_t3_input/xsec
  tracedata: ARIEL/TrainingData/Ground
    Truth Package/Tracedata.hdf5
model:
  posterior_kwargs:
    activation: gelu
    batch_norm: true
    context_with_glu: false
    dropout: 0.0
    hidden_dims_layers:
    - 128
    - 256
    - 512
    - 1024
    - 512
    - 256
    - 128
    multiplicative_factor_layers: 2
    sigma_min: 0.001
    theta_with_glu: true
    time_prior_exponent: -0.5
    type: DenseResidualNet
  prior:
    type: StandardNormal
  type: flow_matching
task:
  name: adc
training:
  batch_size: 64
  device: cuda
  early_stopping: true
  epochs: 450
  num_workers: 0
  optimizer:
    lr: 0.0005
    type: adam
  patience: 400
  scheduler:
    T_max: 150
    type: cosine
  train_fraction: 0.95
