dataset:
  path: data/
evaluation:
  aux_data: ARIEL/TrainingData/AuxillaryTable.csv
  beta: 0.8
  cia_path: ARIEL/ADC_t3_input/cia/HITRAN
  n_quantiles: 10
  n_repeats: 2048
  opacity_path: ARIEL/ADC_t3_input/xsec
  tracedata: ARIEL/TrainingData/Ground Truth Package/Tracedata.hdf5
predictors:
  Baseline (CNN):
    eval_dir: competitors/ADC2023-baseline/output_tf
    color: '#E04900'
  Ex-o-plain:
    eval_dir: competitors/Ex-o-plain/output_ns
    color: '#E09100'
  NSF:
    eval_dir: competitors/Ariel_Data_Challenge_2023_solution/outputs
    color: '#916C29'
  NS:
    eval_dir: ns_runs
    color: '#914A27'
  FMPE (IUAN-P):
    eval_dir: batch_runs/dt_FullNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250220_111529
    color: '#470141'
  FMPE (IUAZ-P):
    eval_dir: batch_runs/dt_FullStandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_14/mfl_2/dropout_0.1/a_-0.75/lr_0.0001/20250220_114102
    color: '#243566'
  FMPE (IUAZ-A):
    eval_dir: batch_runs/dt_FullStandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250220_113323
    color: '#207791'
  FMPE (RUAN-A):
    eval_dir: batch_runs/dt_RealFullNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250221_081629
    color: '#00BDF5'