dataset:
  path: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/data
evaluation:
  aux_data: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/ARIEL/TrainingData/AuxillaryTable.csv
  beta: 0.8
  cia_path: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/ARIEL/ADC_t3_input/cia/HITRAN
  n_quantiles: 10
  n_repeats: 2048
  opacity_path: /home/mgo/Desktop/untested/low-matching-posterior-estimation/ARIEL/ADC_t3_input/xsec
  tracedata: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/ARIEL/TrainingData/Ground
    Truth Package/Tracedata.hdf5
predictors:
  FN-P:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_FullNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250220_111529
    color: blue
  FN-A:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_FullNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_14/mfl_2/dropout_0.0/a_-0.75/lr_0.0001/20250220_003610
    color: red
  FS-P:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_FullStandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_14/mfl_2/dropout_0.1/a_-0.75/lr_0.0001/20250220_114102
    color: darkturquoise
  FS-A:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_FullStandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250220_113323
    color: brown
  RFN-P:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_RealFullNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250221_083207
    color: darkgoldenrod
  RFN-A:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_RealFullNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250221_081629
    color: darkviolet
  RFS-P:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_RealNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250222_004230
    color: chocolate
  RFS-A:
    eval_dir: /home/mgo/Desktop/untested/flow-matching-posterior-estimation/sbi-ariel/batch_runs/dt_RealNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.0/a_-0.75/lr_0.0001/20250221_181340
    color: mediumvioletred