dataset:
  path: data/
evaluation:
  aux_data: ARIEL/TrainingData/AuxillaryTable.csv
  beta: 0.8
  cia_path: ARIEL/ADC_t3_input/cia/HITRAN
  n_quantiles: 10
  n_repeats: 2048
  opacity_path: ARIEL/ADC_t3_input/xsec
  tracedata: ARIEL/TrainingData/Ground Truth Package/Tracedata.hdf5
predictors:
  IN-P:
    eval_dir: batch_runs/dt_NormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.0/a_-0.75/lr_0.0005/20250408_170620
    color: '#F4E8C1'
  IN-A:
    eval_dir: batch_runs/dt_NormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.0/a_-0.75/lr_0.0005/20250408_170620
    color: '#A0C1B9'
  IZ-P:
    eval_dir: batch_runs/dt_StandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_14/mfl_2/dropout_0.1/a_-0.75/lr_0.0005/20250410_082430
    color: '#70A0AF'
  IZ-A:
    eval_dir: batch_runs/dt_StandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_14/mfl_2/dropout_0.0/a_-0.75/lr_0.0001/20250409_194542
    color:  '#706993'

  IUN-P:
    eval_dir: batch_runs/dt_NoisyNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_14/mfl_2/dropout_0.1/a_-0.75/lr_0.0001/20250413_231258
    color: '#4281A4'
  IUN-A:
    eval_dir: batch_runs/dt_NoisyNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250413_224509
    color: '#48A9A6'
  IUS-P:
    eval_dir: batch_runs/dt_NoisyStandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250415_011216
    color: '#D4B483'
  IUZ-A:
    eval_dir: batch_runs/dt_NoisyStandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_14/mfl_2/dropout_0.1/a_-0.75/lr_0.0001/20250415_010313
    color: '#C1666B'


  RUN-P:
    eval_dir: batch_runs/dt_RealNoisyNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.0/a_-0.75/lr_0.0001/20250415_142547
    color: '#B1CF5F'
  RUN-A:
    eval_dir: batch_runs/dt_RealNoisyNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_14/mfl_2/dropout_0.1/a_-0.75/lr_0.0001/20250416_031231
    color: '#478978'
  RUZ-P:
    eval_dir: batch_runs/dt_RealNoisyStandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250417_052635
    color: '#8B95C9'
  RUZ-A:
    eval_dir: batch_runs/dt_RealNoisyStandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250417_051503
    color: '#ACD7EC'

  RAN-P:
    eval_dir: batch_runs/dt_RealNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250222_004230
    color: '#413620'
  RAN-A:
    eval_dir: batch_runs/dt_RealNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.0/a_-0.75/lr_0.0001/20250221_181340
    color: '#9C6615'
  RAZ-P:
    eval_dir: batch_runs/dt_RealStandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250222_023924
    color: '#9F7833'
  RAZ-A:
    eval_dir: batch_runs/dt_RealStandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.0/a_-0.75/lr_0.0001/20250221_183205
    color: '#FFD791'

  IUAN-P:
    eval_dir: batch_runs/dt_FullNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250220_111529
    color: '#C9D6EA'
  IUAN-A:
    eval_dir: batch_runs/dt_FullNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_14/mfl_2/dropout_0.0/a_-0.75/lr_0.0001/20250220_003610
    color: '#B8C4BB'
  IUAZ-P:
    eval_dir: batch_runs/dt_FullStandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_14/mfl_2/dropout_0.1/a_-0.75/lr_0.0001/20250220_114102
    color: '#663F46'
  IUAZ-A:
    eval_dir: batch_runs/dt_FullStandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250220_113323
    color: '#3C362A'

  RUAN-P:
    eval_dir: batch_runs/dt_RealFullNormalizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250221_083207
    color: '#392F5A'
  RUAN-A:
    eval_dir: batch_runs/dt_RealFullNormalizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250221_081629
    color: '#D1495B'
  RUAZ-P:
    eval_dir: batch_runs/dt_RealFullStandardizedArielDataset/p_StandardNormal/m_plain/theta_emb_0/layers_14/mfl_2/dropout_0.0/a_-0.75/lr_0.0001/20250221_002919
    color: '#FF8811'
  RUAZ-A:
    eval_dir: batch_runs/dt_RealFullStandardizedArielDataset/p_StandardNormal/m_autoencoder/theta_emb_0/layers_7/mfl_1/dropout_0.1/a_-0.75/lr_0.0001/20250221_095003
    color: '#00798C'
 


